### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by ddiakopoulos** [ducha-aiki/pymagsac#1]
Hi @ducha-aiki - I just thought I'd let you know that the author of the MAGSAC algorithm licensed his repository under the GPL this morning (https://github.com/danini/magsac/blob/master/LICENSE), so you'll need to update this repository to reflect the GPL as well - this codebase can't be licensed under MIT and anyone who uses this would mistakenly violate his license!

**Comment by ducha-aiki** [comment]
@danini took care of it :) Thanks for pointing this out 
https://github.com/ducha-aiki/pymagsac/commit/4098b9048aa8b56c427ab511d9a71d3337118c9e
